# Generated by Django 4.1.7 on 2023-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_bio_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePhotoUrl',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilePhotos'),
        ),
    ]
