# Generated by Django 4.1.7 on 2023-03-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_profilephotourl_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='crate',
            new_name='create',
        ),
        migrations.AddField(
            model_name='profile',
            name='edit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
